OUTPUT := e2e_tests
$(OUTPUT).pdf: \
	$(OUTPUT).tex \
	../beamer/beamerthemeredhat.sty \
	tex/input_images.tex \
	tex/intro.tex \
	tex/pipeline.tex \
	tex/releases.tex \
	tex/test_types.tex
include ../Makefile
