FROM klakegg/hugo:0.111.3-ext-ubuntu as builder

COPY . /src/

RUN set -x && ln -s /bin/bash /usr/bin/bash && make generate

FROM klakegg/html-proofer:3.18.5

COPY --from=builder /src/public/ /src/public/
