OUTPUT := ci-operator
$(OUTPUT).pdf: \
	$(OUTPUT).tex \
	../beamer/beamerthemeredhat.sty \
	tex/history.tex \
	tex/motivation.tex \
	tex/arch/overview.tex \
	tex/arch/initialization.tex \
	tex/arch/job.tex \
	tex/etc.tex
include ../Makefile
